name: 01-building-blocks
on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building Blocks..."
  
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
           echo "Job success here"
           exit 0
           echo "Building more blocks..."
      - name: say goodbye
        run: echo "goodbye"
