name: 04-using-actions
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04_using_actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Run unit Tests
        run: npm run test
        
    # we could have also done like run: | cd 04_using_actions/react-app
    # npm ci   
    # run command npm ci will run inside the working directory to get .json and lock-json. 
    # Checkout the repo code. 
    # Install Dependency of our react App.
    # Execute automated tests.
